import Head from 'next/head'
import Link from 'next/link'
import Slider from "../components/Slider";

function RulesPage() {
    return (
        <>
       <Slider />
        </>
    )
}
export default RulesPage




{/*return (
        <>
        <div>
        <Head>
        <title>Modal In NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <TestModals />
    </div>
        </>


https://s3.envato.com/files/165244545/background_part_07.png

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoIWzMxAVH0pRN-CLWR5rGPsKWm_9EShnRnki9SdsikwWC8gts1YZDtmGl8uUEOEumMTQ&usqp=CAU

https://t3.ftcdn.net/jpg/01/10/19/24/240_F_110192401_5BM3ZXErqNx8ZEyv35662hvF61Bs3a6z.jpg

https://cdn.wallpapersafari.com/33/74/LCuWhn.png


    )*/}

      
        
  